apiVersion: v2
name: converse-frontend
description: Converse Frontend UI (TypeScript) served by nginx (bjw-s app-template)
type: application

version: 0.1.0

# Tracks the container image tag by default
appVersion: "sha-1d554a6"

keywords:
  - converse
  - frontend
  - ui
  - typescript

dependencies:
  - name: app-template
    version: 4.6.2
    repository: https://bjw-s-labs.github.io/helm-charts
    alias: conversefrontend
