openapi: 3.1.0
info:
  title: lightbridge-authz-api
  description: ''
  contact:
    name: Stephane Segning
    email: selastlambou@gmail.com
  license:
    name: MIT
    identifier: MIT
  version: 0.6.5
paths:
  "/api/v1/accounts":
    get:
      tags:
      - accounts
      operationId: list_accounts
      parameters:
      - name: offset
        in: query
        required: true
        schema:
          type: integer
          format: int32
          minimum: 0
      - name: limit
        in: query
        required: true
        schema:
          type: integer
          format: int32
          minimum: 0
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Account"
    post:
      tags:
      - accounts
      operationId: create_account
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CreateAccount"
        required: true
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Account"
  "/api/v1/accounts/{account_id}":
    get:
      tags:
      - accounts
      operationId: get_account
      parameters:
      - name: account_id
        in: path
        description: Account ID
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Account"
    delete:
      tags:
      - accounts
      operationId: delete_account
      parameters:
      - name: account_id
        in: path
        description: Account ID
        required: true
        schema:
          type: string
      responses:
        '204':
          description: No Content
    patch:
      tags:
      - accounts
      operationId: update_account
      parameters:
      - name: account_id
        in: path
        description: Account ID
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UpdateAccount"
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Account"
  "/api/v1/accounts/{account_id}/projects":
    get:
      tags:
      - projects
      operationId: list_projects
      parameters:
      - name: account_id
        in: path
        description: Account ID
        required: true
        schema:
          type: string
      - name: offset
        in: query
        required: true
        schema:
          type: integer
          format: int32
          minimum: 0
      - name: limit
        in: query
        required: true
        schema:
          type: integer
          format: int32
          minimum: 0
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Project"
    post:
      tags:
      - projects
      operationId: create_project
      parameters:
      - name: account_id
        in: path
        description: Account ID
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CreateProject"
        required: true
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Project"
  "/api/v1/api-keys/{key_id}":
    get:
      tags:
      - api_keys
      operationId: get_api_key
      parameters:
      - name: key_id
        in: path
        description: API key ID
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ApiKey"
    delete:
      tags:
      - api_keys
      operationId: delete_api_key
      parameters:
      - name: key_id
        in: path
        description: API key ID
        required: true
        schema:
          type: string
      responses:
        '204':
          description: No Content
    patch:
      tags:
      - api_keys
      operationId: update_api_key
      parameters:
      - name: key_id
        in: path
        description: API key ID
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UpdateApiKey"
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ApiKey"
  "/api/v1/api-keys/{key_id}/revoke":
    post:
      tags:
      - api_keys
      operationId: revoke_api_key
      parameters:
      - name: key_id
        in: path
        description: API key ID
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ApiKey"
  "/api/v1/api-keys/{key_id}/rotate":
    post:
      tags:
      - api_keys
      operationId: rotate_api_key
      parameters:
      - name: key_id
        in: path
        description: API key ID
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/RotateApiKey"
        required: true
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ApiKeySecret"
  "/api/v1/projects/{project_id}":
    get:
      tags:
      - projects
      operationId: get_project
      parameters:
      - name: project_id
        in: path
        description: Project ID
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Project"
    delete:
      tags:
      - projects
      operationId: delete_project
      parameters:
      - name: project_id
        in: path
        description: Project ID
        required: true
        schema:
          type: string
      responses:
        '204':
          description: No Content
    patch:
      tags:
      - projects
      operationId: update_project
      parameters:
      - name: project_id
        in: path
        description: Project ID
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UpdateProject"
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Project"
  "/api/v1/projects/{project_id}/api-keys":
    get:
      tags:
      - api_keys
      operationId: list_api_keys
      parameters:
      - name: project_id
        in: path
        description: Project ID
        required: true
        schema:
          type: string
      - name: offset
        in: query
        required: true
        schema:
          type: integer
          format: int32
          minimum: 0
      - name: limit
        in: query
        required: true
        schema:
          type: integer
          format: int32
          minimum: 0
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/ApiKey"
    post:
      tags:
      - api_keys
      operationId: create_api_key
      parameters:
      - name: project_id
        in: path
        description: Project ID
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/CreateApiKey"
        required: true
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ApiKeySecret"
components:
  schemas:
    Account:
      type: object
      required:
      - id
      - billing_identity
      - created_at
      - updated_at
      properties:
        billing_identity:
          type: string
        created_at:
          type: string
          format: date-time
        id:
          type: string
        owners_admins:
          type: array
          items:
            type: string
        updated_at:
          type: string
          format: date-time
    ApiKey:
      type: object
      required:
      - id
      - project_id
      - name
      - key_prefix
      - created_at
      - status
      properties:
        created_at:
          type: string
          format: date-time
        expires_at:
          type:
          - string
          - 'null'
          format: date-time
        id:
          type: string
        key_prefix:
          type: string
        last_ip:
          type:
          - string
          - 'null'
        last_used_at:
          type:
          - string
          - 'null'
          format: date-time
        name:
          type: string
        project_id:
          type: string
        revoked_at:
          type:
          - string
          - 'null'
          format: date-time
        status:
          "$ref": "#/components/schemas/ApiKeyStatus"
    ApiKeySecret:
      type: object
      required:
      - api_key
      - secret
      properties:
        api_key:
          "$ref": "#/components/schemas/ApiKey"
        secret:
          type: string
    ApiKeyStatus:
      type: string
      enum:
      - active
      - revoked
    CreateAccount:
      type: object
      required:
      - billing_identity
      properties:
        billing_identity:
          type: string
    CreateApiKey:
      type: object
      required:
      - name
      properties:
        expires_at:
          type:
          - string
          - 'null'
          format: date-time
        name:
          type: string
    CreateProject:
      type: object
      required:
      - name
      - billing_plan
      properties:
        allowed_models:
          type:
          - array
          - 'null'
          items:
            type: string
        billing_plan:
          type: string
        default_limits:
          oneOf:
          - type: 'null'
          - "$ref": "#/components/schemas/DefaultLimits"
        name:
          type: string
    DefaultLimits:
      type: object
      properties:
        concurrent_requests:
          type:
          - integer
          - 'null'
          format: int32
        requests_per_day:
          type:
          - integer
          - 'null'
          format: int32
        requests_per_second:
          type:
          - integer
          - 'null'
          format: int32
    Project:
      type: object
      required:
      - id
      - account_id
      - name
      - billing_plan
      - created_at
      - updated_at
      properties:
        account_id:
          type: string
        allowed_models:
          type:
          - array
          - 'null'
          items:
            type: string
        billing_plan:
          type: string
        created_at:
          type: string
          format: date-time
        default_limits:
          oneOf:
          - type: 'null'
          - "$ref": "#/components/schemas/DefaultLimits"
        id:
          type: string
        name:
          type: string
        updated_at:
          type: string
          format: date-time
    RotateApiKey:
      type: object
      properties:
        expires_at:
          type:
          - string
          - 'null'
          format: date-time
        grace_period_seconds:
          type:
          - integer
          - 'null'
          format: int64
        name:
          type:
          - string
          - 'null'
    UpdateAccount:
      type: object
      properties:
        billing_identity:
          type:
          - string
          - 'null'
        owners_admins:
          type:
          - array
          - 'null'
          items:
            type: string
    UpdateApiKey:
      type: object
      properties:
        expires_at:
          type:
          - string
          - 'null'
          format: date-time
        name:
          type:
          - string
          - 'null'
    UpdateProject:
      type: object
      properties:
        allowed_models:
          type:
          - array
          - 'null'
          items:
            type: string
        billing_plan:
          type:
          - string
          - 'null'
        default_limits:
          oneOf:
          - type: 'null'
          - "$ref": "#/components/schemas/DefaultLimits"
        name:
          type:
          - string
          - 'null'
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
- bearer_auth: []
tags:
- name: accounts
  description: Account management
- name: projects
  description: Project management
- name: api_keys
  description: API key management
